version: "3.9"
services:
  web:
    container_name: "web"
    build: .
    command: gunicorn django_project.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - "DEBUG=False"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
      - "DB_PASSWORD=postgres"
      - "DB_HOST=db"
      - "DB_PORT=5432"
    depends_on:
      - db
  db:
    container_name: "db"
    image: postgres:13
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  nginx:
    container_name: "nginx"
    image: nginx:1.23-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/archive/rss.hazadus.ru/:/certs
      - ./uploads:/uploads
    restart: always