# Generated by Django 4.2.5 on 2023-10-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feed",
            options={
                "ordering": ["-created"],
                "verbose_name": "feed",
                "verbose_name_plural": "feeds",
            },
        ),
    ]
