# Generated by Django 4.2.5 on 2023-10-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={
                "ordering": ["-pub_date"],
                "verbose_name": "entry",
                "verbose_name_plural": "entries",
            },
        ),
    ]
