# Generated by Django 4.2.5 on 2023-10-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0003_alter_entry_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="pub_date",
            field=models.DateTimeField(verbose_name="publication date"),
        ),
    ]
