name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    container: python:3.10.2-slim-bullseye

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Lint Code
        run: python -m isort --check-only --profile black . && flake8 .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container: python:3.10.2-slim-bullseye

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
      rabbitmq:
        image: rabbitmq:3.10.7-management
        env:
          RABBITMQ_DEFAULT_USER: rmuser
          RABBITMQ_DEFAULT_PASS: rmpassword

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        env:
          SECRET_KEY: "django-test-key"
          DB_NAME: postgres
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: db
          DB_PORT: 5432
          CELERY_BROKER_URL: amqp://rmuser:rmpassword@rabbitmq:5672//
        run: python -m manage collectstatic && python -m manage test
