name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    container: python:3.10.2-slim-bullseye

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Lint Code
        run: python -m isort --check-only --profile black . && flake8 .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container: python:3.10.2-slim-bullseye

    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        env:
          SECRET_KEY: "django-test-key"
        run: docker compose up -d && docker exec web python -m manage test
