name: Run Tests
on: [pull_request, workflow_call]

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    container: python:3.10.2-slim-bullseye

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        env:
          SECRET_KEY: "django-test-key"
        run: make test